trigger: none

pool:
  name: App_Pool

stages:
- stage: tf_install
  jobs:
  - job: Tf
    displayName: terraform install ho rha hai
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

- stage: initialize
  jobs:
  - job: init
    displayName: init ho rha hai
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'App_SC'
        backendAzureRmStorageAccountName: 'tfstgankit'
        backendAzureRmContainerName: 'pipetest'
        backendAzureRmKey: '- task: TerraformTask@5'